env: mec_gym

env_args:
  map_name: "trial1" # others can be found in magent.py
  min_x: -100
  max_x : 100
  min_y : -100
  max_y : 100
  max_motor_velocity : 7.5
  motor_acceleration : 7.5
  wheel_radius : 1.8895
  track_width : 9
  wheelbase_length : 11
  max_time : 10
  timestep : 0.1
mask_flag: False
global_state_flag: False
opp_action_in_cc: True